services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ironandspice
    ports:
      - "5432:5432"
    volumes:
      - iron_spice_pg:/var/lib/postgresql/data

volumes:
  iron_spice_pg:
